### ISSUE TITLE
unable to parse masscan output

### ISSUE THREAD

**Issue by miss85246** [zan8in/masscan#2]
I use your demo, wen I run it, it's  raise "unable to parse masscan output"
what should I do ?
```
scanResult:  <nil>
2021/03/14 09:29:58  masscan encountered an error: unable to parse masscan output, see warning for details
exit status 1
```

**Comment by zan8in** [comment]
@miss85246 
1. Confirm that masscan is installed correctly on your system and can be used normally 
2. Determine whether the following command is running normally 
`masscan 146.56.202.100/24 -p 80 --wait=0 --rate=10000 -oJ -`
3. Switch windows and linux to test
4. Try the latest asynchronous scanning function, it's even better

**Comment by zan8in** [comment]
masscan (> 1.3.0)
